version: '3.9'

networks:
  laravel:


services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_app_lain
    ports:
      - "8088:80"
    volumes:
      - ./src/backend_app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: mysql_backend
    restart: unless-stopped
    tty: true
    ports:
      - "5036:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MSQYL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    image: php:8.0.2-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_backend
    volumes:
      - ./src/backend_app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
